changelogFile: ./.liquibase/Data_alias/changelog.xml
driver: org.mariadb.jdbc.Driver
url: jdbc:mariadb://localhost:3306/adito_data_designer
username: adito
password: adito
classpath: C:\\Users\\f.adler\\Documents\\vscode\\Liquibase\\src\\resources\\.liquibase\\mariadb-java-client-2.5.3.jar;C:\\Users\\f.adler\\Documents\\vscode\\Liquibase\\src\\resources\\.liquibase