image: node:18

stages:
  - build
  - sonar
  - deploy
  - release

.basic_build:
  stage: build
  script:
    - echo "foo1"
    - echo "foo2"

build1:
  extends: .basic_build
  script:
    - !reference [.basic_build, script]
    - echo "bar"

build2:
  extends: .basic_build
  script:
    - echo "baz"
