image: node:18

stages:
  - build
  - sonar
  - deploy
  - release

include:
  - local: "basic.gitlab-ci.yml"

build_and_test:
  extends: .basic_build
  script:
    - !reference [.basic_build, script]
    # create config for multi-mocha-reporter
    - |
      echo '{
        "reporterEnabled": "spec, mocha-junit-reporter"
      }' > mocha-multi-reporters.json
    # Dependency for code coverage
    - npm install -g c8
    # Running ESLint and saving the results in a file
    - npm run lint -- --format json --output-file eslint-results.json || true
    # Running tests while generating test result and coverage reports
    - xvfb-run -a npm run test -- --coverage --coverage-output ./coverage --coverage-reporter lcovonly --reporter mocha-multi-reporters  --reporter-options configFile=mocha-multi-reporters.json
  artifacts:
    when: always
    expire_in: 5 days
    reports:
      junit: xunit.xml
    paths:
      - eslint-results.json
      - coverage/lcov.info
      - "./out/src/**"
      - "README.md"
      - "tsconfig.json"
      - "package.json"
      - "CHANGELOG.md"

e2e_tests:
  extends: .basic_build
  before_script:
    - !reference [.basic_build, before_script]
    # add extra package for merging mocha config
    - apt update
    - apt install -y jq
    # let the node user own the current directory
    - chown -R node:node .
  script:
    - !reference [.basic_build, script]
    # add additional options to .mocharc.json
    - |
      jq '.reporter = "mocha-multi-reporters" | .["reporter-option"] = "mocha-multi-reporters.json"' .mocharc.json > .mocharc.temp.json
      mv .mocharc.temp.json .mocharc.json
    # and create options for
    - |
      echo '{
        "reporterEnabled": "spec,mocha-junit-reporter"
      }' > mocha-multi-reporters.json
    # Running tests with a storage directory inside the project directory
    - su node -c "xvfb-run -a npm run test:e2e -- --storage ./out/test-resources"
  artifacts:
    when: always
    expire_in: 5 days
    reports:
      junit: xunit.xml
    paths:
      - "./out/test-resources/screenshots/**"
