changelogFile: changelog.xml
driver: org.mariadb.jdbc.Driver
url: jdbc:mariadb://localhost:3306/adito_data_designer
username: adito
password: adito
classpath: mariadb-java-client-2.5.3.jar
liquibase.hub.mode=off
